### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rudyal1804** [l33tnoob/ido_kernel-kali#1]
hallo friend
i have problem, after "make -j4"
at the end result

make[1]: Nothing to be done for 'dtbs'.
make[1]: Nothing to be done for 'dtbs'.
make[1]: *** No rule to make target 'arch/arm64/boot/dts/msm8939-qrd-wt88509_64.dtb', needed by 'arch/arm64/boot/Image.gz-dtb'.  Stop.
make: *** [/home/rudy/Downloads/kernel/ido_kernel-kali/arch/arm64/Makefile:87: Image.gz-dtb] Error 2

please what should i do

my phone redmi 3
arm64
https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b  nougat-release toolchain64

thanks for your attention

**Comment by l33tnoob** [comment]
You should create symlink from arch/arm/boot/dts/qcom to arch/arm64/boot/dts/qcom
